server:
  port: 80
spring:
  datasource:
    username: root
    password: yz1234567
    url: jdbc:mysql://localhost:3306/yz?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    cache: false